<?php
/**
 * @file
 * gcfsikno_blog.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function gcfsikno_blog_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Population Growth',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '0406571d-ce2a-43fc-b5a5-009f54c9593a',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'gender',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '04e3c108-e722-41d7-87d1-95203d5b87c3',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'gcfsi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0f803934-5f65-4433-b618-4e27aa48cdde',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'gender',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0ff9bc4b-5014-4e09-8342-fdc5c9c68f0c',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Knowledge Asymmetry',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '10b8982a-1ecf-4631-b4c2-cd2db68e6694',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'mytopic',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1727f689-e3ec-4c42-b1e2-e18695c0e98c',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'higher education',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '17bd5bc5-4e49-4b59-b9c7-6ecab9f420c0',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Gwyn',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1ace6548-3656-4eea-a179-6c041087aa25',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Postharvest loss',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1b74a7a2-5cb8-426f-8623-5d7d22ec2d2d',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Cocoa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1bf21ad1-91a9-4e23-a9d7-6ea5a3bc772b',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Smallholder Farmers',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1dd159b8-63b9-4842-97cc-8132d6f879f8',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Transformation of Food Systems',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '2479876d-7de0-41d8-810a-8bcae019beec',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Innovation System',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '26f29ffa-66d5-4899-9069-389a627bc79a',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'entrepreneurship',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2d31d301-bd17-4b8f-92d2-ee295e81baf7',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Scaling',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3088a2cd-7bab-45aa-9a15-960a38d8964a',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'street trading',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '324b9496-791a-4d0c-aa4b-b782560d005f',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'David Tschirley',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '326cd17f-dddf-4669-b8d2-106c73d307c3',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Climate Change',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '3411fb24-1feb-4055-b8d0-96e48efc04b1',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'livelihoods',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '38ef0a63-61ee-42a5-9789-fc96bb07c512',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Chip Steinfield',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '395b180f-8c44-4a1b-b983-aefe065f8013',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Agroecology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3a7dac5f-0666-4dad-81d8-e7aae52465bb',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Food Systems',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3dfeecfb-abc7-49b1-9e77-4d9a9607e829',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Pouyan Nejadhashemi',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4180c4ac-080c-4433-bcf5-d9e897e272c0',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Rwanda',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '41916838-08c3-4074-8e79-032011875498',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Todd Shunneson',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '421ad61c-0b43-4985-be22-7d65f070e5f7',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'informal livelihood',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '43a0ef4c-e662-42eb-a47e-006b97c5fc4b',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'ICT Infrastructure',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '441fa222-b43d-4687-aa1c-c6a137dca1b1',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Tom Smith',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '46244655-c04a-4490-95dc-f5ef1f136b1a',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Africa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '46b34849-519b-4be0-b585-2b6ef28532a0',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'higher education',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '46db872b-6a3b-4b13-8de4-ad2356a65a02',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Nathalie Me-Nsope',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4ab7b844-080a-4b40-b3d0-a25fdfa1683c',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Rapid Ubanization',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '4c60f0a7-48aa-470a-bb67-c4cdd75092de',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Jennifer Olson',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4d373ad1-f9fd-4ca5-9eeb-4da9fa1b5db8',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Education',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '509ab12f-9e3a-48c7-9edd-ee55e3ff02d6',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Gwyn Shelle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '51502cb0-1249-4694-aef9-d3c24ecd911f',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Refrigeration',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '53011a29-3aa8-4e9e-9a6c-8a6cdf377c41',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'urban food systems',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '571e8107-0d41-4225-aeb1-e04776af14fe',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Rural Women',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '58c34e1d-5b5b-424a-8d07-067c84c55bc2',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Use of Cellular Technology for Agricultural Purposes',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5ee80850-b660-4c84-94ea-b790feba9ecb',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'urbanization',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5fbcab59-acf2-4d83-8672-fda1b7a5d6c4',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Agroecology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6798cbd4-b121-4fb7-b878-db91f6fa3325',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Alejandro Guzman',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '67a16161-383c-41c3-8580-7b630803a7fc',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'World Bank',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ab9b9f7-5410-4e4d-9fba-15fd64389002',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Food Security',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ae08aef-cbae-4035-823e-8a22cfb13394',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Henk Renting',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6f91df7e-fff3-4282-9805-1a48ddf0c9b9',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'ICT4D',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7177c209-0a06-4f80-aff5-5a871323accd',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Michael Dolislager',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '739a6c95-4619-4418-9eb7-f9dcc8e25896',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Stephanie White',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '765badde-9514-484c-89da-6dab6b8a8cf5',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'urban food systems',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '76ac5c14-4d67-4fe6-ac1a-02f23231603d',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'John Dirkx',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '77c43f4e-00ff-4c0c-8d5d-8a704c53d28c',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Frugal Innovation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '833cb7fd-f5ba-4c91-805b-5699565247e1',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Small-scale farming',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8368ca37-a000-4a9c-bbaa-5b23e0c35427',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Global Markets',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8647299e-56ab-4591-923f-6439bd99490f',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Energy Use',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8bc3a5f9-824a-4c12-9599-e3ceed505815',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Women Farmers',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8fabb3a6-a833-430c-a20c-792b1fa9cbc5',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Eleanor Doyle',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '90f46b75-0046-49e6-9205-ac564181f1d9',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'information resources',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '92d61ce9-c5b5-4a00-8609-8c2e1638a3b4',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Informal Economy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '934ac276-02b5-4db1-a521-ada66e4c4023',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'MSU Global',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '94ef8220-f3d2-4ad4-83a2-10c0670f3a47',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Small Food Innovation System',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9fb67b8d-55fd-4acf-8a68-72729e5b5035',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'coffee',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9fe7efba-b431-4d56-9388-c3668bc46235',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Innovation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a1447f80-1221-4440-af37-3717f6775ac4',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Charles McKeown',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a25e4e6b-6299-4d35-b916-9a0edfae57d5',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Mallory Flanders',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a2704eec-991d-41c6-8e92-7f27d4f06257',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Innovation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a337def7-0fb8-4ed2-a9a9-a11e6621f239',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'testing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a819048a-ef58-4cbc-affb-12b52f3aa20a',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'sub-Saharan Africa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a8d0437c-302f-4083-9b43-de3a3e08e4a3',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'USAID',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aea9e371-1517-4d6c-b176-55b18763db6b',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Conference',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b44a31ab-1b44-4202-a41f-fd2bec6982c4',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Knowledge Platform',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b5baca27-739e-4caf-b1e9-afdece5b27aa',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Innovation Systems',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b638b0d9-8e75-49b3-b1b2-cfae9b82bfd7',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Blogging',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b85c70b0-08f5-4b04-8ff8-3726acb89a3e',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Agriculture',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b93a1fdb-9eee-40ef-b1ae-8711e84dd150',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Workforce Development',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'bc646f88-d67e-4e84-b9b7-eef90866f471',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Africa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bcda4bf0-c90b-4062-b0bc-3d3ca845e644',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'test',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bd707122-2725-4b2e-aa49-a6ae3bb519ff',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Skills Development',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c83297e5-19e0-485a-85c1-140932bfdc33',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Knowledge Asymmetry',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c8f7918a-02b3-4425-8874-52f6bf55df3d',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Joe Messina',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cab54e6a-f035-40a0-94d4-80eb8bb47ea1',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Agricultural Extension Services',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cc08e7e4-6262-4550-a785-1cc37092f8a1',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'urban economies',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cfd522e5-3dea-4f83-b2c3-abe7576b1a15',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'measuring food systems',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd2725684-14a2-47ef-8782-730b2615ed45',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Climate Change',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd3ef0912-5ce6-419f-8304-0f67d79c50da',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Poverty alleviation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd4704fc8-efad-41a1-8f02-b458c467534d',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'GCFSI-MSU',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd8262324-243c-4ef0-92ca-875dd1f28a21',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Malawi - Mulanje Massif',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'db8c4487-327d-4567-9ecd-95718a7ab50e',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Sieg Snapp',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dfb7d864-9f20-46a4-84dd-ea2d2e85345d',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Informal Economy and Food Security',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e200176c-a362-403c-ae62-cdd1c427fc82',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Informal Economy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e3bffb71-03e5-4d8a-812f-d4a7c6fa79d7',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'livelihood',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e5c231b8-572b-4067-9f49-0f6b85e1215d',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Informal economies',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e6e8a65e-8e44-4b6d-98b8-ba4a8b27b045',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Smallholder Farmers',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e8f01ab1-c72d-4691-9a42-681be57a8bd9',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Urbanization',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ea1dfcf8-9ad5-45d4-a684-dec0220a6827',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'United Nations',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ea70ca2c-f564-45f6-ada8-625198d3daa7',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'entrepreneurship',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eb861721-3762-4ce1-967c-b841a4d8f12d',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'resilience vs efficiency',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ed883967-b770-4407-9173-9edaf00ed4f2',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'The Economist',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ee77ce6b-60c5-4030-aa1b-e54fd89c71e1',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'Refrigeration',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f1d543dc-30d9-4606-9b4d-96dcadb1751c',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Rwanda',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f574be78-258b-4ca3-a569-b18f354a0ca0',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'urbanization and food security',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f800ad10-f208-4638-9e40-241406e755b4',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'sub-Saharan Africa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f81edb50-affe-4ba7-9416-d6f9b3290332',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Pressure on Land',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f90b6d6c-ee30-43c1-a50c-ebb2c788bf89',
    'vocabulary_machine_name' => 'topics',
  );
  $terms[] = array(
    'name' => 'Cindy L McCourt',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f90ced8d-17fe-4699-9467-10f34431c73c',
    'vocabulary_machine_name' => 'document_authors',
  );
  $terms[] = array(
    'name' => 'coffee',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fab79fb9-184c-4ece-9454-7c7dc82aed2f',
    'vocabulary_machine_name' => 'topics',
  );
  return $terms;
}
