<?php
/**
 * @file
 * gcfsikno_blog.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function gcfsikno_blog_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'gender',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '04e3c108-e722-41d7-87d1-95203d5b87c3',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Knowledge Asymmetry',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '10b8982a-1ecf-4631-b4c2-cd2db68e6694',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Cocoa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1bf21ad1-91a9-4e23-a9d7-6ea5a3bc772b',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Innovation System',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '26f29ffa-66d5-4899-9069-389a627bc79a',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'street trading',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '324b9496-791a-4d0c-aa4b-b782560d005f',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Agroecology',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3a7dac5f-0666-4dad-81d8-e7aae52465bb',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Food Systems',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3dfeecfb-abc7-49b1-9e77-4d9a9607e829',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'informal livelihood',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '43a0ef4c-e662-42eb-a47e-006b97c5fc4b',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'higher education',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '46db872b-6a3b-4b13-8de4-ad2356a65a02',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'urbanization',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5fbcab59-acf2-4d83-8672-fda1b7a5d6c4',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'urban food systems',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '76ac5c14-4d67-4fe6-ac1a-02f23231603d',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Small-scale farming',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8368ca37-a000-4a9c-bbaa-5b23e0c35427',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Global Markets',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8647299e-56ab-4591-923f-6439bd99490f',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'information resources',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '92d61ce9-c5b5-4a00-8609-8c2e1638a3b4',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Informal Economy',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '934ac276-02b5-4db1-a521-ada66e4c4023',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'coffee',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9fe7efba-b431-4d56-9388-c3668bc46235',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Innovation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a337def7-0fb8-4ed2-a9a9-a11e6621f239',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'testing',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a819048a-ef58-4cbc-affb-12b52f3aa20a',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Africa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bcda4bf0-c90b-4062-b0bc-3d3ca845e644',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'urban economies',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cfd522e5-3dea-4f83-b2c3-abe7576b1a15',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Climate Change',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd3ef0912-5ce6-419f-8304-0f67d79c50da',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'livelihood',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e5c231b8-572b-4067-9f49-0f6b85e1215d',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Informal economies',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e6e8a65e-8e44-4b6d-98b8-ba4a8b27b045',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Smallholder Farmers',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e8f01ab1-c72d-4691-9a42-681be57a8bd9',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'United Nations',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ea70ca2c-f564-45f6-ada8-625198d3daa7',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'entrepreneurship',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eb861721-3762-4ce1-967c-b841a4d8f12d',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Refrigeration',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f1d543dc-30d9-4606-9b4d-96dcadb1751c',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'Rwanda',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f574be78-258b-4ca3-a569-b18f354a0ca0',
    'vocabulary_machine_name' => 'categories',
  );
  $terms[] = array(
    'name' => 'sub-Saharan Africa',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f81edb50-affe-4ba7-9416-d6f9b3290332',
    'vocabulary_machine_name' => 'categories',
  );
  return $terms;
}
